### ISSUE TITLE
searching and managing large tilesets is difficult, possible solution

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot-proposals#1094]
**Describe the project you are working on:**
platform shooter

**Describe the problem or limitation you are having in your project:**
tilemap editor makes finding items long-winded and difficult, especially when large tilesheets are used. Specifically, knowing which tiles have collision or other polygons and finding tiles using the Pick Tile option seems to have a bug. Detailed next.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
1. In the picture below there are lots of tiles, but only some have collision (or possibly occlusion and navigation) polygons. There is no way to know which of the tiles have them currently, only the currently selected tile (as shown).

![image](https://user-images.githubusercontent.com/12863685/85203906-a5bda180-b308-11ea-95f3-d3b7e40cd9ef.png)

2. I would consider this more a bug than a feature request. When you use the Pick Tile option it does not scroll to make the selection visible. When you have a lot of tiles, it's time consuming to scroll up and down to figure out where the tile is. The image below shows the picked tile, but I had to scroll for quite a few seconds to find it.

![image](https://user-images.githubusercontent.com/12863685/85203950-f9c88600-b308-11ea-8433-23f93f74409e.png)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
1. Have a checkbox 'show all' on the tileset toolbar so that when you select 'collision', 'occlusion', 'navigation', if the checkbox it ticked, all the polygons are shown for that tile. Something like this, or completely different :)

![image](https://user-images.githubusercontent.com/12863685/85204192-a5bea100-b30a-11ea-9697-c24dbd58a987.png)

2. When Pick Tile is used, simply ensure the tile is visible on screen.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it is a feature that should be present to make tile maps more usable.

**Comment by KoBeWi** [comment]
Related to #896

**Comment by chucklepie** [comment]
I don't think that topic has anything related. That is about other things.

**Comment by Calinou** [comment]
> 3. I would consider this more a bug than a feature request. When you use the Pick Tile option it does not scroll to make the selection visible. When you have a lot of tiles, it's time consuming to scroll up and down to figure out where the tile is. The image below shows the picked tile, but I had to scroll for quite a few seconds to find it.

I tried to implement this, but it seems like it's already supposed to be the case. The [tilemap editor's `_pick_tile()` method](https://github.com/godotengine/godot/blob/7a62b94bcae4da685144ce11aa6f1c8ad19b7c71/editor/plugins/tile_map_editor_plugin.cpp#L590-L617) calls `set_selected_tiles()` which in turn [calls `ensure_current_is_visible();` on the palette ItemList](https://github.com/godotengine/godot/blob/7a62b94bcae4da685144ce11aa6f1c8ad19b7c71/editor/plugins/tile_map_editor_plugin.cpp#L256). I tried calling it twice, calling it with `call_deferred()` and calling it in `_pick_tile()` directly (before and after `set_selected_tiles()` to no avail).

Any pointers?

**Comment by Jummit** [comment]
I think instead of using a list, a grid layout as seen in most tilemap editors would be better.

**Comment by Calinou** [comment]
@groud Is this addressed by the new TileMap and TileSet editor in 4.0?

**Comment by KoBeWi** [comment]
Looking at the new tile editor...
1. The property painting mode allows you to see e.g. collision shapes of all tiles, so this is implemented.
2. Looks like it's not possible, but not sure why would you need that (unless I misunderstood something).
3. This is less relevant because tiles are now presented as palette rather than list, but seems like the editor still doesn't focus on the picked tile.

@chucklepie  I'd suggest giving the new tile editor a try. It doesn't exactly resolve all issues listed here, but it's a huge improvement compared to the old one, so these issues might become non-issues.
You can get a semi-official 4.0 build here: https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20210811/

**Comment by chucklepie** [comment]
I think 2 will be fixed by the toggle Tilemap collision shapes update when
it is completed (forgotten the id, but it still had a few outstanding bugs
last time I looked at the issue on github)

**Comment by KoBeWi** [comment]
Then it's resolved already.
So the only thing left is half of 3, i.e. editor doesn't auto-focus on picked tile, but it's not as much of a problem now.
