### ISSUE TITLE
Add analytical Gaussian-blurred shadows to StyleBoxFlat

### ISSUE THREAD

**Issue by sockeye-d** [godotengine/godot-proposals#13755]
### Describe the project you are working on

UI heavy application

### Describe the problem or limitation you are having in your project

The default shadows look kind of bad. They're forced to be fully opaque in the area the StyleBox occupies, making them look too hard when offset, and since it just offsets the normal rounded corner geometry, they can look stiff.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Gaussian blur shadows, like the ones used by web engines, often look much better, even if they are technically less physically accurate.

Also, a Gaussian blur of a rectangle can be computed analytically as the integral of two boxcar functions (one for x, one for y), resulting in no actual blurring needing to happen.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add a flag `use_gaussian_shadow` to StyleBoxFlat, and use a shader like https://www.shadertoy.com/view/3cKczh to render the regular shadow geometry. (made by me, based on [Fast Rounded Rectangle Shadows - Made by Evan](https://madebyevan.com/shaders/fast-rounded-rectangle-shadows/)).

Limitations:
* It'd be a little slower
* The shadow will technically get cut off by the geometry as the Gaussian function has infinite support
* It only supports analytically blurred square corners instead of rounded ones. The article linked describes how to use mixed analytical and numerical integration to properly shadow rounded boxes, but at high sigmas nobody's likely to notice anyway

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

StyleBoxFlat's shadows can't be modified with an addon

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/3494
and https://github.com/godotengine/godot-proposals/issues/13353.

> and use a shader like [shadertoy.com/view/3cKczh](https://www.shadertoy.com/view/3cKczh) to render the regular shadow geometry

StyleBoxFlat does not require the use of custom shaders. Implementing this functionality with a shader would be pretty complex. The shadow alone would have to be split to its own CanvasItem, then drawn with a custom shader.

Instead, implementing this with vertex colors like the current shadow should be much simpler. The approach would be similar to emulating cubic gradient falloff with a linear gradient (you just add more points to the gradient to get the desired falloff). It might be a bit slower due to the mesh generation taking more time, but this will greatly reduce implementation complexity.

**Comment by sockeye-d** [comment]
Hm, that's a good point. Maybe it's possible to do something like https://www.shadertoy.com/view/lfcXDl and displace the coordinates of the shadow mesh instead?

**Comment by Samvkes** [comment]
I'm taking a stab at implementing this with multiple stacked transparent vertex-color shadows. These all have a stack of 4 shadow "rings" (instead of the normal 1).

<img width="1919" height="1038" alt="Image" src="https://github.com/user-attachments/assets/875b3337-2df1-4d03-8f27-2cd1bb2e59bf" />

**Comment by sockeye-d** [comment]
Those look great! One thing I'm concerned with is banding, since you basically quarter your available color depth if you have 4 layers, and it only gets worse from there. Is it possible to make multiple rings rather than just the inner and outer rings, then adjust each one's brightness to have a more gaussian-cdf falloff?

**Comment by Samvkes** [comment]
Hey, I worded it a bit awkwardly but what (I think) you're describing is what I'm currently doing: 4 strips are "stacked" from inside to out, and at the start and end of each strip they sample a gaussian falloff (inside each strip the falloff is linear, since it's just vertex colors). Here I've made the strips more visible: 

<img width="674" height="634" alt="Image" src="https://github.com/user-attachments/assets/015adf6e-9a2a-4800-8442-1ca2e275155c" />

Banding is a real issue, though I think it gets a lot better with more strips. Here's 3 vs 12:

<img width="995" height="453" alt="Image" src="https://github.com/user-attachments/assets/fda886d4-a753-4f01-b179-81db62995957" />

<img width="896" height="340" alt="Image" src="https://github.com/user-attachments/assets/de853ee0-1515-4c28-ad5d-3a32e697de5e" />

I've done some tests with not distributing the ring thickness evenly (doing thinner rings near the start or end) but I don't think it necessarily looks better. 
For the falloff I'm just using https://www.desmos.com/calculator/2fkbdrlg3m with c being shadow_size / 3

I'll try to post a pr today or tomorrow, if you'd like to look at the implementation.

Also, for this to really work you'd split up Size into Blur and Spread (that's also what Figma and some other tools do). But that's maybe for a different pr.

**Comment by sockeye-d** [comment]
@Samvkes I'm not sure how you're doing the math right now, but if you're sampling the distribution directly from x = 0.0 to x = 1.0, that's wrong since you need to be sampling the integral of the distribution from 0 to x (also known as the "error function"). You can see that when offset, the error function's falloff (blue) looks a little like the normal distribution's (green), which is why they look _similar_:

<img width="1231" height="623" alt="Image" src="https://github.com/user-attachments/assets/9c9964a1-7ca9-4505-a34f-08dfc67046c3" />

<img width="1536" height="961" alt="Image" src="https://github.com/user-attachments/assets/b0060209-62fc-4235-b327-5806114b0e94" />

The middle one I generated from [this](https://en.wikipedia.org/wiki/Error_function#Approximation_with_elementary_functions) error function approximation:

```gdscript
func _erf_approx(x: float) -> float:
	var sgn_x := signf(x)
	x = absf(x)
	return (1.0 - 1.0 / pow(1 + 0.278393 * x + 0.230389 * x*x + 0.000972 * x*x*x + 0.078108 * x*x*x*x, 4.0)) * sgn_x
```

Also, it's pretty closely approximated with

```gdscript
ease(t_from_0_to_1, -2.6)
```

**Comment by Samvkes** [comment]
I've made some adjustments, now it uses the erf approximation @sockeye-d linked. Below is different shadow sizes, with 4 layers for the 2 shapes on the left, and 12 layers for the ones on the right.

<img width="1316" height="889" alt="Image" src="https://github.com/user-attachments/assets/56e5a40d-e958-430c-a357-43ddb725a1c6" />

The transition between pure black and the shadow is still a bit harder than I'd like...

**Comment by sockeye-d** [comment]
Is your code on your fork? Is it okay for me to play around with it a bit?

**Comment by Samvkes** [comment]
I just pushed it, and of course!

**Comment by sockeye-d** [comment]
I've tweaked it by making the rounded corner radius based on the maximum of the shadow size times some coefficient and the corner radius, I think it looks better for sharp corners like the top left corner:

<img width="217" height="233" alt="Image" src="https://github.com/user-attachments/assets/faf7145d-5f84-422b-83b7-bdfb67489938" />

It's close to a real Gaussian-blurred shadow but still not perfect, but I think it handles large radii better

https://github.com/user-attachments/assets/59d3898e-33f5-420d-9e62-3e236c4d4c81

<img width="368" height="372" alt="Image" src="https://github.com/user-attachments/assets/42349942-51cf-49cf-b772-851b66517d10" />

Also, how would you feel about defaulting the bands to 6? It's 50% more geometry but I think the visual gain over 4 is significant.

Here's the patch for my changes: [make-shadow-prettier.patch](https://github.com/user-attachments/files/25362555/make-shadow-prettier.patch)

**Comment by Samvkes** [comment]
Hey, I've integrated your patch and pushed a new commit. The code is kind of a mess right now, but functionality-wise I think this is kinda what I'd like to submit as a pr. I've added some checks so the shape no longer self-intersects at larger shadow sizes (because of the inner ring shrinking). That currently assumes that Height is the smallest dimension of the stylebox, so that obviously needs to be fixed still.

I agree with you about setting a higher default for the bands, at the same time, I've also been considering if we should just leave out the toggle for switching between standard and gaussian shadows, and instead make it so that at 0 bands it does the standard shadow, and at 1+ it does a gaussian. Then we'd use 0 as a default.

I've also done a little bit of benchmarking, a scene with hundreds of panels w/ styleboxes changing size every frame (forcing them to redraw). With the standard shadows I can have ~400 panels in a scene at around 60fps, with 8 shadow bands I can do ~200 panels before I drop below 60fps. So might be nice to see if it can be made a bit faster.

Lastly, since shadow size is now no langer capped by self-intersection, I've made it so that overall shadow opacity slowly decreases at very large shadow sizes (similarly to how Figma does drop-shadows). I think this makes it feel more realistic since the total amount of shadow stays constant, but it does mean you have slightly less artistic control.

**Comment by sockeye-d** [comment]
Editor UX-wise, maybe you could turn it into one of those sections with the toggles? Like this one

<img width="401" height="590" alt="Image" src="https://github.com/user-attachments/assets/2552976b-0f82-4b50-b6fa-e4bf9daa6854" />

That way if ever in the future an override for like shadow corner radius or something gets added it can go there too
