### ISSUE TITLE
Improve the animation Bezier editor

### ISSUE THREAD

**Issue by reduz** [godotengine/godot-proposals#3141]
### Describe the project you are working on

Godot

### Describe the problem or limitation you are having in your project

Common user complains about editing animation beziers. More specifically:

* Only one track at the same time can be edited.
* Only visibility to the current node is allowed.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The idea is to overcome both those issues.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The plan is as follows:

* By default, any point of any visible Bezier curve track will be editable/selectable/etc. instead of the selected track.
* Selecting a single point on any visible curve, or just clicking the curve itself will cause the track on the track list to be selected.
* Selecting single points always has priority for the selected track, this helps avoid issues when many points of several tracks overlap.
* Locking tracks is possible on the list to the left thanks to new lock buttons. Only those locked will be selectable (if any is locked)
* A **Scope menu** will be present, allowing visibility of all tracks in the animation or just on the current node. Changing this is dependent on the current selected track at the time the mode is changed.
* **Handle menu** also converted to buttons, this is easier to use as it requires a single click to switch.
* Closing the editor has always been confusing, so a proper close button is also added.

Mock up (editor is kind of broken on Master, but you get the idea):

![image](https://user-images.githubusercontent.com/6265307/129451444-57a228a8-4bfa-4b54-84da-49eb1c31f545.png)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no script can do this.

### Is there a reason why this should be core and not an add-on in the asset library?

animation editor is core.

**Comment by georgesboris** [comment]
> Locking tracks is possible on the list to the left thanks to new lock buttons. Only those locked will be selectable (if any is locked)

I wonder if this should be the opposite? As in locked tracks cannot be selected by accident. This is usually how things work on design tools but I'm unsure if it's different on animation tools.

**Comment by bonbonmiel** [comment]
I too would advocate for "locking curves" to mean locking them _out_ of edits (just like nodes in scenes).
The "locking" functionality described here is more of a "selectable/editable" state than a locked one so I believe this would have to be either renamed or see its behavior flipped.
For the record, blender has these icons for (un)selectable objects:
![image](https://user-images.githubusercontent.com/71937306/129453118-91686229-5706-49bf-a8f9-772232ef2954.png)

**Comment by SilencedPerson** [comment]
> > Locking tracks is possible on the list to the left thanks to new lock buttons. Only those locked will be selectable (if any is locked)
> 
> I wonder if this should be the opposite? As in locked tracks cannot be selected by accident. This is usually how things work on design tools but I'm unsure if it's different on animation tools.

> I too would advocate for "locking curves" to mean locking them _out_ of edits (just like nodes in scenes).
> The "locking" functionality described here is more of a "selectable/editable" state than a locked one so I believe this would have to be either renamed or see its behavior flipped.
> Blender also uses a locked state for editing curves but it's the opposite: locked curves _cannot_ be edited.

as an animator, my initial reaction was pretty much the same, however, i would like to give this approach a try, it seems to me like it could save quite a lot of clicks.

**Comment by reduz** [comment]
Indeed, I don't see the use case of leaving out a single track. On the contrary when you have lots of tracks, focusing in just a few but keeping the rest as reference is a lot more useful.

**Comment by Error7Studios** [comment]
Or maybe have 2 buttons, like a DAW.

![Mute Solo](https://user-images.githubusercontent.com/60025044/129454725-b93cecfa-0c1e-497f-b5fa-d4326bca5e8c.png)

When you have 8 tracks, it's faster to `Solo` a track than to `Mute` the other 7.

**Comment by SilencedPerson** [comment]
> Indeed, I don't see the use case of leaving out a single track. On the contrary when you have lots of tracks, focusing in just a few but keeping the rest as reference is a lot more useful.

the only thing i would change, is the name from `lock` to `focus` to avoid confusion.

**Comment by reduz** [comment]
@SilencedPerson well its an icon so it does not show a text.. maybe a different icon?

**Comment by reduz** [comment]
@Error7Studios In a DAW it makes complete sense to solo and mute tracks, here excluding a track does not make sense.

**Comment by SilencedPerson** [comment]
> @SilencedPerson well its an icon so it does not show a text.. maybe a different icon?
then i suggest the visibility eye from the scene tree. but only show the full eye and greyed out eye instead of the closed one.
![image](https://user-images.githubusercontent.com/82024211/129455531-4c2fa522-594a-4be3-907d-71843c69c074.png)

**Comment by tinmanjuggernaut** [comment]
I'd like some sort of auto scale, auto fit / find key frames, and separate scales per track features. Usually value ranges have wildly different scales. I click on rotation, then pan and zoom to find values 0-360. Then click on a translation which could be values at 0-1 or 0-2000. When Animating one object, I'm constantly going back and forth between translation and rotation, so there is constant adjustment of the display so I can find the key frames. 

Ideally I'd be able to get multiple curves on screen at once and be able to go back and forth to adjust them, meanwhile the scale is silently adjusting on the side. No manual adjustment of the display is needed, once I have it set up. No popping of the display as it automatically changes to view different scales. Instead just a stable display where only the numbers change and the curves stay there unless I change them, or change the window scaling or panning. 

So I'd recommend:
* per track scale or global scale modes
* If i click a track, or select key frames it would be natural to press F to auto scale around the whole track or selected key frames (Y axis only). 
* if I select all tracks, or no tracks and press F, it scales around everything. This would do different things in pts or gs modes. In pts mode it would normalize the curves on individual scales. In gs mode, normalize everything on one scale. 
* in pts, clicking another track just updates the scale numbers, but doesn't move the curve unless I move the key frames or display. 
* A or ctrl+A could select all key frames. 

Also we desperately need channel mute in the bezier editor. It's very annoying to have to go back to the regular editor to mute, then come back into bezier to adjust. 

Solo mode is helpful, especially if you have an animation with 20-30 channels and need to figure out which one is causing the problem. Alternatively an enable /disable all tracks button would work fine. (main editor and bezier) 

Other requests 
* Duplicate duplicates the key frame(s) at the cursor, overwriting whatever was there. Instead let the duplicated key frames hover with my mouse until I click or press enter to set them, or esc to cancel.

* space bar should play / stop. Home and end should go to those places on the timeline.

**Comment by Arrow-x** [comment]
Adding a lattice deform tool will be very useful
![GUID-9065EB8A-B6AB-426D-B1C4-79E591816BEB](https://user-images.githubusercontent.com/3308421/129475935-27400819-4eca-4aff-b5b9-1a372bc28187.gif)

**Comment by NathanLovato** [comment]
> excluding a track does not make sense

It totally does, animators use that. I think it'd be good to get professional game animators in there, or people who worked on the animation editor UX in Blender in the discussion if possible, as they know very well what the users need.

So, hiding several tracks or isolating them are both useful. It's quite common to work in isolation on a bunch of curves when doing animation cleanup and those can be a bit arbitrary: it might be the transforms of several nodes, e.g. isolating just the legs' transforms, or a single arm on a character, etc. That's similar to solo tracks in DAWs in a sense.

Then locking is useful too: you keep the tracks for reference of how the values change, of timing, but you don't want to select and modify them inadvertently. For example when animating a character's tail, to properly animate follow-through.

To me, Blender is an excellent example when it comes to the animation editors: you can select multiple tracks from the left column and either toggle their visibility (leftmost icon), isolate them (shortcut: Shift H hides unselected as in the rest of Blender, alt H unhides everything), or lock them.

![Screenshot from 2021-08-15 10-29-01](https://user-images.githubusercontent.com/12694995/129485453-6959209c-3f14-4660-8eb6-6edc4bb20848.png)

Back when I did animation (I studied 3d character animation for games specifically), I'd get to use all that on pretty much every animation.

**Comment by LillyByte** [comment]
Bezier curves feel too far disconnected from everything else.

Might wanna look at this old proposal that's been sitting around forever too, where this issue was also discussed:

https://github.com/godotengine/godot-proposals/issues/392

**Comment by NathanLovato** [comment]
I asked @reduz if we could take care of this proposal at GDQuest and he said ok. So we'll get to work on this in the coming weeks!

**Comment by TokageItLab** [comment]
This is an explanation of Auto-tangent and Extend handle in some animation applications, which I discussed with @NathanLovato on Contributors Chat before.

![handle_point](https://user-images.githubusercontent.com/61938263/133884024-4e107022-8208-4fca-955d-dc653cbd9434.jpg)

Both behave similarly. However, I personally feel that the one based on Balanced is smoother, because the handle length is equal between keyframes.

**Comment by NathanLovato** [comment]
Very clear, thanks. I'll likely make a separate proposal before adding all the above. Making handle mode a property of keyframes is already in progress: https://github.com/godotengine/godot-proposals/issues/3236

**Comment by Razoric480** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/2823241/141504615-dc2e1407-6935-40f2-87d2-b20f140fe9fe.png)

### Implementation list

- All bezier curves drawn and selectable simultaneously
- Can select a track by selecting one of its keys, or by clicking on the curve itself. Will prioritize the currently 'main selected' track since it's sorted first.
  - Selecting multiple tracks will set the first one in the list as main selected.
- Fixed visual bugs. TextLine's introduction in 4.0 already takes string height into account so it was breaking rendering.
- Moved the bezier track toggle from a track-button to being on the toolbar. This obsoletes the `X Close` button, so I removed it.
- As it's based off of #53298 , handle modes are part of keys now, and without the handle mode menu, that left the right column empty, so I nixed it.
- reduz mentioned a scope feature, but we already have the ability to filter by selected node as part of the track editor - so instead of re-implementing the feature, now the bezier editor responds to node filtering.
- The ability to lock (visible but grayed out and unselectable), hide (invisible), solo (hides all except one) or delete tracks from the bezier editor (instead of having to close the editor, delete a track, re-open the editor...)
- Some bug/omission fixes - in track editor, the trash can was kind of falling off half way down the right side, and moving the name limit space didn't move the bezier editor's, so now they're properly tied together.

### Issue not sure how to proceed to fix

The default 150 pixels for the name limit is too small for the bezier editor and you end up with the icons overlapping the track names, but there's no way to change the name limit from outside, so the user has to extend it beforehand. Not sure if changing the default magic number of 150 would be appreciated, but it'd have the least knock-on effects or change of math.

### Considerations

Animation software (like blender, maya, etc), when you have multiple keys selected and you move a bezier handle, all of the keys' handles move simultaneously by the relative amount. It wasn't implemented in 3.x, so I didn't put it here, but it could be a feature we'd think about.

Still need #53298 to be merged since I made my branch off of that before I go and make a PR so I don't double any commits/conflicts, then can go through a review process with code cleanup suggestions, but I'm close to done otherwise.

**Comment by TokageItLab** [comment]
Can we close this since https://github.com/godotengine/godot/pull/64647 has been merged? Are there any features still missing?

**Comment by fire** [comment]
Closing due the request for clarification being from last year.

I encourage you to make a new issue or proposal.
